"""
Train the AI-SOC detection models.

Two models are trained side by side so the project can show both approaches:

1. Isolation Forest (unsupervised) — trained only on the feature matrix,
   no labels used. This is what you'd run in a real deployment where you
   don't have confirmed-malicious examples yet: it just learns what "normal"
   looks like and flags anything that doesn't fit.

2. Random Forest classifier (supervised) — trained using the `attack_present`
   ground-truth label generated by the synthetic data. This represents the
   deployment stage after you've accumulated confirmed incidents to train on,
   and is used here mainly to give a clean precision/recall number to report.

Both are evaluated against a held-out test split so you get real numbers,
not vibes.
"""

import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import IsolationForest, RandomForestClassifier
from sklearn.metrics import classification_report, precision_recall_fscore_support
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

ROOT = Path(__file__).resolve().parents[2]
FEATURES_PATH = ROOT / "data" / "features.csv"
MODELS_DIR = ROOT / "src" / "models" / "artifacts"
MODELS_DIR.mkdir(exist_ok=True)

FEATURE_COLUMNS = [
    "event_count",
    "failed_login_count",
    "distinct_dst_ports",
    "distinct_dst_ips",
    "distinct_users",
    "total_bytes_out",
    "max_bytes_out",
    "hour",
    "is_weekday",
]


def main():
    df = pd.read_csv(FEATURES_PATH)
    X = df[FEATURE_COLUMNS].fillna(0)
    y = df["attack_present"].astype(int)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.3, random_state=42, stratify=y
    )

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)

    # --- Unsupervised: Isolation Forest, trained on normal-only rows ---
    normal_only = X_train_scaled[y_train.values == 0]
    iso_forest = IsolationForest(
        n_estimators=300, contamination=0.03, random_state=42
    )
    iso_forest.fit(normal_only)

    iso_pred_raw = iso_forest.predict(X_test_scaled)  # -1 = anomaly, 1 = normal
    iso_pred = (iso_pred_raw == -1).astype(int)
    iso_scores = -iso_forest.score_samples(X_test_scaled)  # higher = more anomalous

    p, r, f1, _ = precision_recall_fscore_support(
        y_test, iso_pred, average="binary", zero_division=0
    )
    print("=== Isolation Forest (unsupervised) ===")
    print(classification_report(y_test, iso_pred, target_names=["normal", "attack"], zero_division=0))

    # --- Supervised: Random Forest classifier ---
    rf = RandomForestClassifier(
        n_estimators=300, max_depth=10, class_weight="balanced", random_state=42
    )
    rf.fit(X_train_scaled, y_train)
    rf_pred = rf.predict(X_test_scaled)
    rf_proba = rf.predict_proba(X_test_scaled)[:, 1]

    p2, r2, f12, _ = precision_recall_fscore_support(
        y_test, rf_pred, average="binary", zero_division=0
    )
    print("=== Random Forest (supervised) ===")
    print(classification_report(y_test, rf_pred, target_names=["normal", "attack"], zero_division=0))

    # --- Save artifacts ---
    joblib.dump(iso_forest, MODELS_DIR / "isolation_forest.pkl")
    joblib.dump(rf, MODELS_DIR / "random_forest.pkl")
    joblib.dump(scaler, MODELS_DIR / "scaler.pkl")

    metrics = {
        "isolation_forest": {"precision": p, "recall": r, "f1": f1},
        "random_forest": {"precision": p2, "recall": r2, "f1": f12},
        "feature_columns": FEATURE_COLUMNS,
        "n_train": int(len(X_train)),
        "n_test": int(len(X_test)),
        "n_attack_test": int(y_test.sum()),
    }
    with open(MODELS_DIR / "metrics.json", "w") as f:
        json.dump(metrics, f, indent=2)

    print(f"\nSaved models + metrics to {MODELS_DIR}")
    print(json.dumps(metrics, indent=2))


if __name__ == "__main__":
    main()
